# This `~/.aipack-base/config.toml` file is the base config for all of the aipack workspaces (`.aipack` container folders)

[default_options]
# `model` required to be able to run an agent. 
# This will be the fallback for any workspace that do not defined their model in their config.toml
# (any model supported by the Rust genai crate)
#
# e.g.,    
#          Ollama: "llama3.3:70b", "llama3.1:8b", "llama3.2:3b" "deepseek-r1:8b" "deepseek-coder-v2:16b" (or any locally installed Ollama)
#            Groq: "deepseek-r1-distill-llama-70b", "llama3-8b-8192", "llama-3.3-70b-versatile"
#             xAI: "grok-beta"
#       Anthropic: "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest"
#          OpenAI: "gpt-5", "gpt-5-mini", "gpt-5-nano", or with suffixes "gpt-5-mini-low"
#          Gemini: "gemini-2.0-pro-exp-02-05", "gemini-1.5-pro", "gemini-1.5-flash-8b" 
#        DeepSeek: "deepseek-chat" "deepseek-reasoner" (from deepseek.com)
model = "gpt-5-nano" # or an alias below (e.g. "fast", "cost-saver")

# Temperature (by default unset)
# temperature = 0.0

# How many inputs can be processed at the same time (Defaults to 1 if absent)
# input_concurrency = 6

# Define your own model aliases for any model/provider you have access to, and they can be used in place of the model name.
# This can also be overridden or complemented in the `# Options` section of the aipack.
# Note: It is important to have `model_aliases` as a property of `default_options` as shown below.
[default_options.model_aliases]
standard = "gpt-5"
high     = "gpt-5-high"
low      = "gpt-5-low"
flash    = "gemini-2.5-flash"
claude   = "claude-sonnet-4-20250514"