[package]
name = "devai"
version = "0.0.1"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
description = "Command Agent runner to accelerate production coding. File based, fully customizable, NOT for building snake games."
categories = ["command-line-utilities"]
keywords = ["generative-ai","openai","genai","ai-coding"]
homepage = "https://github.com/jeremychone/rust-devai"
repository = "https://github.com/jeremychone/rust-devai"


[[bin]]
name = "da"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"
unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Async
tokio = { version = "1", features = ["full"] }
# -- AI
# genai = "0.1.8"
genai = { path = "/Users/jeremychone/_jeremy/_rust/utils/rust-genai" }
# -- Json
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# value-ext = "0.0.1"
value-ext = { path = "/Users/jeremychone/_jeremy/_rust/utils/rust-value-ext"}
# -- Template & Scripting
rhai = {version = "1.19", features = ["sync"]}
handlebars = "4"
# -- Cli
clap =  {version = "4.5.17", features = ["cargo", "derive"]}
# -- Files
simple-fs = { version = "0.1", features = ["full"] }
# -- Others
derive_more = {version = "1.0.0-beta", features = ["from"] }
keyring = {version = "3", features = ["apple-native"]}

