[genai]
# Required (any model rust genai crate support)
# e.g., "gpt-4o", "gpt-4o-2024-08-06", "gpt-4o-mini", "claude-3-5-sonnet-20240620"
model = "gpt-4o-mini"

[runtime]
# Default to 1 if absent
items_concurrency = 1 