# This `~/.aipack-base/config.toml` file is the base config for all of the aipack workspaces (`.aipack/` container folders)

# Note: Was `default_options` in `<= 0.7.9` (both still supported, but now use 'options')
[options]

# `model` required to be able to run an agent. 
#         This will be the fallback for any workspace that does not define its model in their config.toml
#         (any model supported by the Rust genai crate)
#
# Support models from: OpenAI, Gemini, Anthropic, Ollama (local), DeepSeek, Groq, Grok(xAI)
#
# e.g., 
#    Ollama: "llama3.3:70b", "llama3.1:8b", "llama3.2:3b", "deepseek-r1:8b", "deepseek-coder-v2:16b" (or any locally installed Ollama)
#    Gemini: "gemini-2.5-pro-preview-05-06", "gemini-2.5-flash-preview-04-17", "gemini-2.5-flash-preview-04-17-zero"
# Anthropic: "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest"
#    OpenAI: "o4-mini", "o4-mini-high", "o4-mini-low", "gpt-4.1, "gpt-4.1-mini",  "gpt-4.1-nano"

model = "gpt-4.1-mini" # or an alias from below (e.g., "flash", "gpro")

# Temperature (by default unset)

# temperature = 0.0

# How many inputs can be processed at the same time (Defaults to 1 if absent)

input_concurrency = 2


# Model Aliases
# Define your own model aliases for any model/provider you have access to, and they can be used in place of the model name.
# This can also be overridden or complemented in the `# Options` section of the aipack, or in the `options` return of before all or data
#
# Note: It is important to have `model_aliases` as a property of `default_options.model_aliases` as shown below.
#
# Change as you see fit. Can be overridden in workspace config.toml `.aipack/config.toml`.
[options.model_aliases]
# -- Anthropic
claude      = "claude-sonnet-4-20250514"
# -- OpenAI
high        = "o4-mini-high"
med         = "o4-mini"
low         = "o4-mini-low"
main        = "gpt-4.1"
mini        = "gpt-4.1-mini"
nano        = "gpt-4.1-nano"
# -- Google
gpro-prev       = "gemini-2.5-pro-preview-05-06"
flash           = "gemini-2.0-flash"
flash-prev      = "gemini-2.5-flash-preview-04-17"
flash-prev-zero = "gemini-2.5-flash-preview-04-17-zero"
# -- Deepseek
r1          = "deepseek-reasoner"
