[genai]
# Required (any model supported by the Rust genai crate)
# e.g.,    OpenAI:  "gpt-4o", "gpt-4o-mini", "o1-mini", "o1-preview"
#       Anthropic: "claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022", "claude-3-haiku-20240307"
#          Gemini: "gemini-1.5-pro", "gemini-1.5-flash", "gemini-1.5-flash-8b" 
#          Ollama: "llama3.3:70b", "llama3.1:8b", "llama3.2:3b" (or any locally installed Ollama)
#             xAI: "grok-beta"
model = "gpt-4o-mini"

# Temperature (by default unset)
# temperature = 0.0

[runtime]
# How many inputs can be processed at the same time
# (Defaults to 1 if absent)
# input_concurrency = 6